using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("Singularity IT")]
[assembly: AssemblyProductAttribute("Did You Work Today?")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2012")]
[assembly: AssemblyTrademarkAttribute("")]

[assembly: AssemblyVersionAttribute("0.5.0.0")]
[assembly: AssemblyFileVersionAttribute("0.5.0.0")]
